theme: minima
title: Volant Notes
author: Flying Az
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Everying doesn't have to be happening in synchronization. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  azvolant
show_excerpts: false # set to false to remove excerpts on the homepage
